---
title: "An Introductory Explainer for Time-Series Analysis"
output:
  html_document:
    keep_md: true
---

<meta property="og:title" content="An Introductory Explainer for Time-Series Analysis">
<meta property="og:description" content="Even for students who are well trained in econometrics/statistics, getting started with time-series analysis can be mystifying.">

<!-- 
<meta property="og:image" content="">
<meta property="og:url" content="">
-->

Nearly all of my research can be described as applied time-series econometrics. When graduate students approach me hoping to start research in this area, they usually have to start from ground zero in terms of their time-series statistical training. Even students well trained in econometrics often have seen little, if any, treatment of time-series techniques because first and even second econometrics courses focus most of their time on cross-sectional and panel techniques.

For the graduate student aspiring to do a (Ph.D.) dissertation or (M.S.) thesis in price analysis this is a real bummer because it often will be 6 to 18 months before they can work a formal time series econometrics course into their schedule, severely delaying their research. 

Students wanting to focus on price analysis often come to me to ask how they can get started learning on their own. I always point them to [Walter Enders'](http://time-series.net/) "[Applied Time Series Econometrics](https://www.amazon.com/Applied-Econometric-Wiley-Probability-Statistics/dp/1118808568/ref=dp_ob_title_bk)", which is a wonderful book and is basically how I learned to 'do time series' when I was under the gun finishing my own dissertation. 

Recently, I found Constantin Colonescu's "[Using R for Principles of Econometrics](http://www.lulu.com/shop/constantin-colonescu/using-r-for-principles-of-econometrics/paperback/product-23467421.html)" (for now, draft is available for free [here](https://bookdown.org/ccolonescu/RPoE4/)). What I really like about this book is that it can be effectively used to both learn applied econometrics, but also it can be used to learn how to do applied econometrics in R. 